# <font color='blue'>FUMEC - Analytics com Python</font>
## **Lista de exercícios 08 - Análise de dados**

<br>**ATENÇÃO:** para salvar o arquivo .ipynb do notebook, faça da seguinte forma:

* **Google Colaboratory**: opção do menu "Arquivo --> Fazer download --> Fazer o download do .ipynb"

* Salve o arquivo com o nome "**SeuNome_lista08.ipynb**"

<br>

### **Importar o arquivo de dados**:

Arquivo de dados que será utilizado na lista de exercícios: "**flights.csv**".

In [4]:
url = 'https://drive.google.com/uc?export=download&id=1zQivO-v75BYa9BKOunaFy5tsRsSmy0ax'
url

'https://drive.google.com/uc?export=download&id=1zQivO-v75BYa9BKOunaFy5tsRsSmy0ax'

### **01) Execute as seguintes tarefas**:

Explorar o dataset "**flights.csv**" utilizando os recursos da biblioteca Pandas.

In [8]:
import pandas as pd

df = pd.read_csv(url)
df.head()

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0

Listar o número de linhas e colunas do dataset

In [10]:
print(df.shape)

(58492, 14)

Listar o nome das colunas do dataset

In [48]:
print(df.columns)

Index(['MONTH', 'DAY', 'WEEKDAY', 'AIRLINE', 'ORG_AIR', 'DEST_AIR',
       'SCHED_DEP', 'DEP_DELAY', 'AIR_TIME', 'DIST', 'SCHED_ARR', 'ARR_DELAY',
       'DIVERTED', 'CANCELLED'],
      dtype='object')

Executar o resumo estatístico do dataset

In [39]:
df.describe()

,MONTH,DAY,WEEKDAY,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
count,58492.000000,58492.000000,58492.000000,58492.000000,57659.000000,57474.000000,58492.000000,58492.000000,57474.000000,58492.000000,58492.000000
mean,6.220646,15.702096,3.926862,1387.984836,10.921192,115.928576,872.900072,1549.399832,5.812315,0.002342,0.015062
std,3.358484,8.760846,1.995777,482.810792,36.146210,71.679591,624.996805,518.599952,38.411948,0.048340,0.121800
min,1.000000,1.000000,1.000000,5.000000,-24.000000,8.000000,67.000000,1.000000,-60.000000,0.000000,0.000000
25%,3.000000,8.000000,2.000000,1000.000000,-4.000000,61.000000,391.000000,1159.000000,-12.000000,0.000000,0.000000
50%,6.000000,16.000000,4.000000,1353.000000,-1.000000,97.000000,690.000000,1603.000000,-4.000000,0.000000,0.000000
75%,9.000000,23.000000,6.000000,1805.000000,10.000000,152.000000,1199.000000,1959.000000,9.000000,0.000000,0.000000
max,12.000000,31.000000,7.000000,2359.000000,1194.000000,577.000000,4502.000000,2359.000000,1185.000000,1.000000,1.000000

Qual o maior valor, a média e a mediana da coluna **'DIST'**

In [17]:
print(df["DIST"].mean())
df["DIST"].median()

872.9000718046913

690.0

Listar os valores únicos da coluna **'AIRLINE'**

In [38]:
print(df["AIRLINE"].unique())

['WN' 'UA' 'MQ' 'AA' 'F9' 'EV' 'OO' 'NK' 'US' 'AS' 'DL' 'VX' 'B6' 'HA']

Listar quantos são os valores únicos da coluna **'AIRLINE'**

In [37]:
print(df["AIRLINE"].nunique())

14

Listar quantos valores existem em cada valor único da coluna **'AIRLINE'**

In [42]:
df["AIRLINE"].value_counts()

AIRLINE
DL    10601
AA     8900
WN     8418
UA     7792
OO     6588
EV     5858
MQ     3471
US     1615
NK     1516
F9     1317
VX      993
AS      768
B6      543
HA      112
Name: count, dtype: int64

Verificar as informações do dataset com o método info()

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58492 entries, 0 to 58491
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MONTH      58492 non-null  int64
 1   DAY        58492 non-null  int64
 2   WEEKDAY    58492 non-null  int64
 3   AIRLINE    58492 non-null  object
 4   ORG_AIR    58492 non-null  object
 5   DEST_AIR   58492 non-null  object
 6   SCHED_DEP  58492 non-null  int64
 7   DEP_DELAY  57659 non-null  float64
 8   AIR_TIME   57474 non-null  float64
 9   DIST       58492 non-null  int64
 10  SCHED_ARR  58492 non-null  int64
 11  ARR_DELAY  57474 non-null  float64
 12  DIVERTED   58492 non-null  int64
 13  CANCELLED  58492 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 6.2+ MB

Listar o total de valores nulos (ausentes) em cada coluna

In [49]:
df.isnull().sum()

MONTH           0
DAY             0
WEEKDAY         0
AIRLINE         0
ORG_AIR         0
DEST_AIR        0
SCHED_DEP       0
DEP_DELAY     833
AIR_TIME     1018
DIST            0
SCHED_ARR       0
ARR_DELAY    1018
DIVERTED        0
CANCELLED       0
dtype: int64

Preencher os valores nulos das colunas **'AIR_TIME'** e **'ARR_DELAY'** com a média dos valores das respectivas colunas

In [50]:
df["AIR_TIME"] = df["AIR_TIME"].fillna(df["AIR_TIME"].mean())
df["ARR_DELAY"] = df["ARR_DELAY"].fillna(df["ARR_DELAY"].mean())

Listar novamente o total de valores nulos de cada coluna

In [51]:
df.isnull().sum()

MONTH          0
DAY            0
WEEKDAY        0
AIRLINE        0
ORG_AIR        0
DEST_AIR       0
SCHED_DEP      0
DEP_DELAY    833
AIR_TIME       0
DIST           0
SCHED_ARR      0
ARR_DELAY      0
DIVERTED       0
CANCELLED      0
dtype: int64

Excluir as linhas do dataset onde ainda existem valores nulos

In [53]:
df = df.dropna(subset=['DEP_DELAY'])

Listar novamente o total de valores nulos de cada coluna

In [54]:
df.isnull().sum()

MONTH        0
DAY          0
WEEKDAY      0
AIRLINE      0
ORG_AIR      0
DEST_AIR     0
SCHED_DEP    0
DEP_DELAY    0
AIR_TIME     0
DIST         0
SCHED_ARR    0
ARR_DELAY    0
DIVERTED     0
CANCELLED    0
dtype: int64

Listar novamente o número de linhas e colunas do dataset

In [55]:
print(df.shape)

(57659, 14)

Listar as linhas do dataset cujo valor da coluna **'AIRLINE'** é igual a **'HA'**

In [57]:
df.loc[df["AIRLINE"] == "HA"]

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
582,1,4,7,HA,LAX,OGG,1115,-11.0,310.0,2486,1500,-27.0,0,0
712,1,5,1,HA,LAS,HNL,900,-5.0,357.0,2762,1315,5.0,0,0
878,1,6,2,HA,PHX,HNL,800,1.0,374.0,2917,1140,3.0,0,0
1053,1,7,3,HA,LAX,HNL,1705,0.0,332.0,2556,2055,-2.0,0,0
1269,1,8,4,HA,LAX,HNL,1000,-1.0,335.0,2556,1350,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55883,12,16,3,HA,LAX,HNL,835,1.0,314.0,2556,1235,-18.0,0,0
56174,12,18,5,HA,LAX,HNL,835,-5.0,342.0,2556,1235,-4.0,0,0
56350,12,19,6,HA,PHX,HNL,800,-5.0,363.0,2917,1155,-34.0,0,0
56816,12,21,1,HA,LAX,LIH,740,20.0,303.0,2615,1145,-11.0,0,0
58391,12,31,4,HA,LAX,HNL,1000,0.0,324.0,2556,1350,-9.0,0,0

Listar as linhas do dataset cujo valor da coluna **'AIRLINE'** é igual a **'HA'** e o valor da coluna **'DEP_DELAY'** é maior do que **20.0**

In [59]:
df.loc[(df["AIRLINE"] == "HA") & (df['DEP_DELAY'] > 20.0)]

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
1345,1,9,5,HA,LAS,HNL,900,27.0,354.0,2762,1315,29.0,0,0
2316,1,15,4,HA,LAX,HNL,1705,22.0,319.0,2556,2055,10.0,0,0
22584,5,13,3,HA,LAX,OGG,1115,22.0,310.0,2486,1350,14.0,0,0
26127,6,1,1,HA,LAS,HNL,900,169.0,365.0,2762,1205,200.0,0,0
31675,7,1,3,HA,LAX,HNL,840,23.0,304.0,2556,1140,-6.0,0,0
37664,8,2,7,HA,PHX,HNL,800,24.0,376.0,2917,1130,31.0,0,0
42165,8,26,3,HA,LAX,LIH,740,50.0,347.0,2615,1045,54.0,0,0
49971,11,10,2,HA,LAX,HNL,835,298.0,338.0,2556,1235,298.0,0,0